name: End-to-end tests
on: [push, pull_request]
env:
  RECORD_REPLAY_CHROMIUM_DOWNLOAD_FILE: linux-chromium-20230621-992a66d7f85d-5e3d79d9768c-buildkite.tar.xz
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.1.0
        with:
          browser: replay-chromium
          build: npm run build
          start: npm start

      # Always run this step so failed tests are uploaded 
      - name: Upload replays
        if: always()
        uses: replayio/action-upload@v0.5.0
        with:
          api-key: rwk_gDtAB8kjJ722fCNiCFZ8hEbsri41eiadNGQ0MxDIcuM
